### ISSUE TITLE
Cannot install latest master with python3

### ISSUE THREAD

**Issue by pdonorio** [irods/python-irodsclient#125]
```
git clone https://github.com/irods/python-irodsclient.git prc
cd prc
pip3 install -e .

Obtaining file:///tmp/test/prc
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/test/prc/setup.py", line 14, in <module>
        long_description = file.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8874: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in ...
```

It seems the Readme file has some non ascii code, so to fix this, you need to specify the encoding in the open. Here's how I fixed it in my fork: [link](https://github.com/pdonorio/python-irodsclient/commit/81909faa342994b45e060513e8dfb41f4a96c674)

**Comment by trel** [comment]
That may be Python 3 only?
  https://github.com/keleshev/schema/issues/68#issuecomment-140489245


Looks like the Python 2 and 3 way to do this is via `codecs`...

```diff
diff --git a/setup.py b/setup.py
index 9f03745..e735453 100644
--- a/setup.py
+++ b/setup.py
@@ -1,4 +1,5 @@
 from setuptools import setup, find_packages
+import codecs
 import os
 
@@ -10,7 +11,7 @@ with open(os.path.join(here, 'irods/version.py')) as file:
 
 # Get description
-with open('README.rst') as file:
+with codecs.open('README.rst', 'r', 'utf-8') as file:
     long_description = file.read()
```

Can you confirm this works for you?

**Comment by pdonorio** [comment]
Yes, I can confirm that this code works with Python3.

**Comment by trel** [comment]
excellent.  thanks!   sorry for the hiccup.
