### ISSUE TITLE
DataObjectManager.copy segfault

### ISSUE THREAD

**Issue by kuntzagk** [irods/python-irodsclient#145]
I'm trying to copy a dataobject, the following code
```
from irods import iRODSSession
session = iRODSSession(...)
dm=session.data_objects
dm.copy("orig_file", "new_file")
```

in rodsLog I find this:
```Dumping stack trace
<0>     Offset:         Address: 0x7f24334ba9fc /lib/libirods_server.so.4.2.4(+0xb0f9fc) [0x7f24334ba9fc]
<1>     Offset:         Address: 0x7f2430bfe680 /lib64/libpthread.so.0(+0xf680) [0x7f2430bfe680]
<2>     Offset: 0x107   Address: 0x7f2433242457 rsDataObjCopy(rsComm_t*, DataObjCopyInp*, transferStat_t**)
<3>     Offset: 0x54    Address: 0x7f24333c53d4 irods::api_call_adaptor<DataObjCopyInp*, transferStat_t**>::operator()(irods::plugin_context&, rsComm_t*, DataObjCopyInp*, transferStat_t**)
<4>     Offset: 0x16    Address: 0x7f24333c5346 std::__1::__function::__func<irods::api_call_adaptor<DataObjCopyInp*, transferStat_t**>, std::__1::allocator<irods::api_call_adaptor<DataObjCopyInp*, transferStat_t**> >, irods::error (irods::plugin_context&, rsComm_t*, DataObjCopyInp*, transferStat_t**)>::operator()(irods::plugin_context&, rsComm_t*&&, DataObjCopyInp*&&, transferStat_t**&&)
<5>     Offset: 0xf35   Address: 0x7f24333122f5 int irods::api_entry::call_handler<DataObjCopyInp*, transferStat_t**>(rsComm_t*, DataObjCopyInp*, transferStat_t**)
<6>     Offset: 0x70f   Address: 0x7f24334e4b7f rsApiHandler(rsComm_t*, int, BytesBuf*, BytesBuf*)
<7>     Offset: 0x8f2   Address: 0x7f24334e6942 readAndProcClientMsg(rsComm_t*, int)
<8>     Offset: 0x9c7   Address: 0x7f24334dad57 agentMain(rsComm_t*)
<9>     Offset: 0x1b6f  Address: 0x7f24334d964f runIrodsAgent(sockaddr_un)
<10>    Offset:         Address: 0x42156d       /usr/sbin/irodsServer(main+0x4cd) [0x42156d]
<11>    Offset:         Address: 0x7f242f8fa3d5 /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f242f8fa3d5]
<12>    Offset:         Address: 0x420fd1       /usr/sbin/irodsServer() [0x420fd1]

Nov 26 14:49:42 pid:1032  ERROR: Agent process [32224] exited with status [11]```

iRODS version is 4.2.4, python-irodsclient is 0.8.0

**Comment by d-w-moore** [comment]
Andreas - I got similar results to yours, when I didn't specify the full data object paths . Have you tried using the full paths? Something like this:
```
# ... (include your code from above)
import irods.keywords as kw
which_collection = "{0}/home/{1}"%(session.zone,session.username)
# (or insert a value for wherever your objects reside)
session.data_objects.copy( 
  "/myzone/home/myuser/data1" , "/myzone/home/myuser/data2", 
  **{kw.FORCE_FLAG_KW : '1' } # -- this is only necessary if you may have to force overwrite
)

```

**Comment by kuntzagk** [comment]
I think I used full object paths and just cut them for brevity.

Sorry, currently I cannot replay that code. I get "CAT_INVALID_AUTHENTICATION" exceptions when I try to access using python client.
I use the same auth data that works on the same machine with icommands.

So might be that something else is buggy in my setup.
```
>>> dm.get("/zoneName/objectPath")
Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/session.py", line 117, in server_version
    conn = next(iter(self.pool.active))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/pool.py", line 23, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/connection.py", line 89, in recv
    err_msg = iRODSMessage(msg=msg.error).get_main_message(Error).RErrMsg_PI[0].msg
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/message/__init__.py", line 171, in get_main_message
    msg.unpack(ET.fromstring(self.msg))
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/xml/etree/ElementTree.py", line 1325, in XML
    parser.feed(text)
TypeError: 'NoneType' does not support the buffer interface

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/manager/data_object_manager.py", line 45, in get
    parent = self.sess.collections.get(irods_dirname(path))
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/manager/collection_manager.py", line 15, in get
    query = self.sess.query(Collection).filter(Collection.name == path)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/session.py", line 96, in query
    return Query(self, *args)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/query.py", line 43, in __init__
    if self.sess.server_version >= col.min_version:
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/session.py", line 120, in server_version
    conn = self.pool.get_connection()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/pool.py", line 25, in get_connection
    conn = Connection(self, self.account)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/connection.py", line 46, in __init__
    self._login_native()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/connection.py", line 455, in _login_native
    self.recv()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irods/connection.py", line 91, in recv
    raise get_exception_by_code(msg.int_info)
irods.exception.CAT_INVALID_AUTHENTICATION: None
```

**Comment by kuntzagk** [comment]
(deleted one comment about CAT_INVALID_AUTHENTICATION exception, this was trying PAM authentication)

Ok, full path names work.

**Comment by trel** [comment]
Okay, so we can return a better error message on the client side, and make sure the server doesn't error out itself.

Thanks.
