### ISSUE TITLE
Errors when trying to execute a previously-registered specific query with arguments

### ISSUE THREAD

**Issue by csklimowski** [irods/python-irodsclient#150]
I'm not sure if this is a bug, or just poor documentation. I have a query registered on an iRODS server with the name "test-query" that I'm trying to execute through the client. I am able to execute it with this icommand:

`iquest --sql test-query /arg/path`

However, when I try to run this:

```python
with iRODSSession(host='...', port='...', user='...', zone='...', password='...') as session:
    query = SpecificQuery(session, alias='test-query', args=['/arg/path'], columns=[DataObject.name])
    for result in query:
        print(result[DataObject.name])
```

I get these errors:

```
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/3.6/lib/python3.6/site-packages/irods/connection.py", line 89, in recv
    err_msg = iRODSMessage(msg=msg.error).get_main_message(Error).RErrMsg_PI[0].msg
  File "/home/chris/.virtualenvs/3.6/lib/python3.6/site-packages/irods/message/__init__.py", line 171, in get_main_message
    msg.unpack(ET.fromstring(self.msg))
  File "/home/chris/.pyenv/versions/3.6.6/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "irods-test.py", line 21, in <module>
    for result_set in query:
  File "/home/chris/.virtualenvs/3.6/lib/python3.6/site-packages/irods/query.py", line 321, in get_results
    for result_set in self.get_batches():
  File "/home/chris/.virtualenvs/3.6/lib/python3.6/site-packages/irods/query.py", line 308, in get_batches
    result_set = self.execute()
  File "/home/chris/.virtualenvs/3.6/lib/python3.6/site-packages/irods/query.py", line 297, in execute
    response = conn.recv()
  File "/home/chris/.virtualenvs/3.6/lib/python3.6/site-packages/irods/connection.py", line 91, in recv
    raise get_exception_by_code(msg.int_info)
irods.exception.CAT_SQL_ERR: None
```

I'm running Python 3.6.6 in a virtualenv.

**Comment by trel** [comment]
Hi @csklimowski, did you find the tests?

https://github.com/irods/python-irodsclient/blob/master/irods/test/query_test.py#L187

**Comment by trel** [comment]
I think this syntax will do what you're looking for?

https://github.com/irods/python-irodsclient/blob/master/irods/test/query_test.py#L265

```
        query = SpecificQuery(self.session, alias='ls')
```

**Comment by csklimowski** [comment]
I figured out the problem.

In `query.py`:

```python
for i, arg in enumerate(self._args[:10]):
            sql_args['arg{}'.format(i)] = arg
```

This results in the arguments being labeled as "arg0", "arg1", "arg2", etc, when they should actually be "arg1", "arg2", "arg3", etc. So, it should really be this:

```python
for i, arg in enumerate(self._args[:10]):
            sql_args['arg{}'.format(i+1)] = arg
```

I'll make a pull request with this change. Thanks for your help!

**Comment by csklimowski** [comment]
#153
