### ISSUE TITLE
on irods branch, USER_PACKSTRUCT_INPUT_ERR when sending keycloak token

### ISSUE THREAD

**Issue by RubenGarcia** [irods/python-irodsclient#177]
The following code

```
with iRODSSession(host='172.17.0.4', port=1247, authentication_scheme='openid',
        openid_provider='keycloak_openid', user="rods",
        zone='tempZone',
        access_token=id,
        ) as session:
        coll_manager = CollectionManager(session)
        coll = coll_manager.get('/tempZone/home/rods')
```
Is giving a `USER_PACKSTRUCT_INPUT_ERR` for the following token:

`id="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJLczJ5eXNLUDRRcXpEWXlPT1NXRF9wa0Q3TW9pTktyQ280ZllPdXBYMUJZIn0.eyJqdGkiOiIzZDNkOGIwYy0wNTljLTQ5ZmQtOTY0MC1lYjcwZjQ0OGM4NTEiLCJleHAiOjE1NzE2NDk5MzcsIm5iZiI6MCwiaWF0IjoxNTcxNjQ5NjM3LCJpc3MiOiJodHRwczovL2tleWNsb2FrLml0NGkuY3ovYXV0aC9yZWFsbXMvTEVYSVMiLCJzdWIiOiJhYjI4ZmFiZi0yY2NiLTRhMTktYmUzOC00MmFmNTQ5YjVkNzciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJpcm9kcy1hdXRoLXBsdWdpbiIsIm5vbmNlIjoiZjNkYjBmOWEwNWExYTdlODliNTJjNTM4MWFiMTNmMzVhMmI2MzYzOWFkMDA1YTU1ZjA4ODMwMTQ4NDc5NThkMiIsImF1dGhfdGltZSI6MTU3MTY0OTYzNywic2Vzc2lvbl9zdGF0ZSI6IjhkZGI1NjNkLWY1YjctNDI0Ni04NjY0LTA0NWZjYzNmMmZiMCIsImFjciI6IjEiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJlbWFpbCI6ImdhcmNpYUBscnouZGUifQ.ZuUad1hfqQDuYxtnZLev4PvKjn_GtMjJRh5-yX8tsCPXRLEXuBmI7tFWGppPqT3-R5eApcgxn9fi7ycfaYO0Jgx_lNIHJ13mxaH79j8HcLYGJOkjzA7OS5w_zdj-J9bRWeeLtHdrBNHkZCXYCTYaRHAoCPtkbwbEpmUmlX-7b8FOqOlLnseQ2tOQEOSlECzfzrM6_yhB7zEQvwz5e05teZGH_-4C8vv0V__ei9C1qD7oimo77vRitHDWZdwNAZgum3grjH8zlxklmHTs-rr0OvnyFjYhJ6u_NuMqvr1ZUkyKVEoBGMc2J9qfREqbV9ei31wEQRq3aLifeZUuyw60SQ"`

The error displayed is:
```
Internal Server Error: /demo/irods
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/irods/session.py", line 117, in server_version
    conn = next(iter(self.pool.active))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/irods/pool.py", line 23, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/irods/connection.py", line 90, in recv
    err_msg = iRODSMessage(msg=msg.error).get_main_message(Error).RErrMsg_PI[0].msg
  File "/usr/local/lib/python3.6/site-packages/irods/message/__init__.py", line 171, in get_main_message
    msg.unpack(ET.fromstring(self.msg))
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/root/django-keycloak-test/demo/views.py", line 78, in irods
    coll = coll_manager.get('/tempZone/home/rods')
  File "/usr/local/lib/python3.6/site-packages/irods/manager/collection_manager.py", line 15, in get
    query = self.sess.query(Collection).filter(Collection.name == path)
  File "/usr/local/lib/python3.6/site-packages/irods/session.py", line 96, in query
    return Query(self, *args)
  File "/usr/local/lib/python3.6/site-packages/irods/query.py", line 43, in __init__
    if self.sess.server_version >= col.min_version:
  File "/usr/local/lib/python3.6/site-packages/irods/session.py", line 120, in server_version
    conn = self.pool.get_connection()
  File "/usr/local/lib/python3.6/site-packages/irods/pool.py", line 25, in get_connection
    conn = Connection(self, self.account)
  File "/usr/local/lib/python3.6/site-packages/irods/connection.py", line 50, in __init__
    self._login_openid()
  File "/usr/local/lib/python3.6/site-packages/irods/connection.py", line 446, in _login_openid
    req_result = self.openid_client_auth_request()
  File "/usr/local/lib/python3.6/site-packages/irods/connection.py", line 408, in openid_client_auth_request
    return self.recv()
  File "/usr/local/lib/python3.6/site-packages/irods/connection.py", line 92, in recv
    raise get_exception_by_code(msg.int_info)
irods.exception.USER_PACKSTRUCT_INPUT_ERR: None
"GET /demo/irods HTTP/1.1" 500 130910
```

**Comment by RubenGarcia** [comment]
It seems there may be a bug in the packing of large tokens (?).
It seems the chain of exceptions is caused by irods returning irods.exception.USER_PACKSTRUCT_INPUT_ERR when unable to decode the token.

**Comment by RubenGarcia** [comment]
This token does not raise the USER_PACKSTRUCT_INPUT_ERR, though

id="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJLczJ5eXNLUDRRcXpEWXlPT1NXRF9wa0Q3TW9pTktyQ280ZllPdXBYMUJZIn0.eyJqdGkiOiJiOTUxOTcxOS0yZDU1LTQ4OTYtOGY0Zi1mNzY1NDYzNDI0MjAiLCJleHAiOjE1NzE2NDk4OTIsIm5iZiI6MCwiaWF0IjoxNTcxNjQ5NTkyLCJpc3MiOiJodHRwczovL2tleWNsb2FrLml0NGkuY3ovYXV0aC9yZWFsbXMvTEVYSVMiLCJhdWQiOiJpcm9kcy1hdXRoLXBsdWdpbiIsInN1YiI6ImFiMjhmYWJmLTJjY2ItNGExOS1iZTM4LTQyYWY1NDliNWQ3NyIsInR5cCI6IklEIiwiYXpwIjoiaXJvZHMtYXV0aC1wbHVnaW4iLCJub25jZSI6IlF6SG9LaHpJNkxQOFdNNVV3cXJuUERZTjl0aUtwdHZQIiwiYXV0aF90aW1lIjoxNTcxNjQ5NTkyLCJzZXNzaW9uX3N0YXRlIjoiOGRkYjU2M2QtZjViNy00MjQ2LTg2NjQtMDQ1ZmNjM2YyZmIwIiwiYWNyIjoiMSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJlbWFpbCI6ImdhcmNpYUBscnouZGUifQ.ZA75DyQMBDTAwZpdHibOW3xKWSGy3Ywum1F3ZfD0V0FuEm-bTjcrDrWa3kxmvJovEEvuHnSV9uX-l54AA1G14Oc-jdK9bw8FjsDenCDVrKD0Z1799MICsz-Kc6xOx9p82I60hmZtKseFtvjfYq34UjvOKEZ_jJRhXfkPexUzMkhZozFT0bvcIDWf64ActOP4AEa_12edHZaXJk4mzsF96QkAoCeNzHKFzZavJIMxANQhgbtwdf-Mb5oOAGbOeJqQA4gqZL5hV7DuhKQ92fdZMhWUxm5jrz92HhNDdKRJ5X29k3YcwMW3SReX9Ml1-WjukOah-YNGxTZhm5UJ9aP6Hw"

**Comment by RubenGarcia** [comment]
Irods server version 4.2.3.

**Comment by RubenGarcia** [comment]
When I use the command line, ils gives me:
`[-]	/root/irods_auth_plugin_openid/src/libopenid.cpp:876:irods::error openid_auth_client_request(irods::plugin_context &, rcComm_t *) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [context string > max name len]
failed with error -130000 SYS_INVALID_INPUT_PARAM`
so there may be a limit on the size of the token on the irods-server <-> irods-client protocol.

**Comment by RubenGarcia** [comment]
Problem has been verified.
To fix this, tokens larger than 1024 bytes should be hashed prior to submission, and the back-end authorization service should search tokens both by full token and by hash in the database, accepting both. An example of such system can be seen in my forks.

**Comment by trel** [comment]
Good to have lunch with you @RubenGarcia.

Yes, the `USER_PACKSTRUCT_INPUT_ERR` signifies a hard limit in the iRODS packing instruction (protocol) itself.  I see you got the hash approach working with iRODS 4.2.3.

You mentioned in person that the same approach did not work against 4.2.6?   That is surprising.  Please share more and we might be able to take some action on this issue.

**Comment by trel** [comment]
I believe this is the reason your code that worked against 4.2.3 is not working against 4.2.6...

https://github.com/irods/irods/issues/4221 removed the clientLoginOpenID() function in 4.2.5.

**Comment by RubenGarcia** [comment]
From my notes (I'll have to check this more slowly in Munich) about using 4.2.6 instead of 4.2.3:
***I recreated the container, and I am no longer getting USER_PACKSTRUCT_INPUT_ERR. However, I am getting a redirectURL, as though the token was not being accepted (!?).

**Comment by RubenGarcia** [comment]
I guess the plugin would not compile if that was the only issue. So in previous versions of irods, one of these functions must have been called by irods itself. The removal of this call would be the culprit of the code no longer working. After that, since the functions were not being called, the patch removed them as "unneeded".
