### ISSUE TITLE
remote zone user cannot be created within the client

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#227]
assuming zone A is properly federated to a zoneB containing a registered rodsuser **alice#zoneB**,

1. if we try to use the _session_.users.create method to create an entry for the zoneB alice,
 
we get the error
```
>>> session.users.create('alice','rodsuser','zoneB','')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/irods/python-irodsclient/irods/manager/user_manager.py", line 42, in create
    response = conn.recv()
  File "/var/lib/irods/python-irodsclient/irods/connection.py", line 101, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_SQL_ERR: DEBUG: 
```
whereas creating a user within the ICAT's own zone is successful
```
session.users.create('alice','rodsuser','zoneA'','') # --> _no error_ creating alice#zoneA
```

2. if in the zoneA ICAT we attempt creating **alice#zoneB**  _after_ having successfully created **alice#zoneA**, we get a different error than the CAT_SQL_ERR in (1) above.
```
>>> session.users.create('alice','rodsuser','zoneA','')
<iRODSUser 10042 alice rodsuser zoneA>
>>> i.users.create('alice','rodsuser','zoneB','')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/irods/python-irodsclient/irods/manager/user_manager.py", line 42, in create
    response = conn.recv()
  File "/var/lib/irods/python-irodsclient/irods/connection.py", line 101, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME: Error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME
```

**Comment by d-w-moore** [comment]
probably the zone hint is not being passed to the ICAT. Although obviously passed as an argument, perhaps the zone name is ignored in the PRC's user creation routines. Perhaps it's rendered empty field in the  XML protocol -- investigating.
