### ISSUE TITLE
Problem with self-signed certificates

### ISSUE THREAD

**Issue by holtgrewe** [irods/python-irodsclient#237]
Via the irods ingest capability... I have irod setup with a self-signed certificate and provide the client server with the corret CA cert. Still I get the following exception trace.

```
Last login: Fri Dec  4 10:58:54 CET 2020
Traceback (most recent call last):
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/session.py", line 127, in server_version
    conn = next(iter(self.pool.active))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/pool.py", line 43, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/irods_sync.py", line 144, in <module>
    main()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/irods_sync.py", line 140, in main
    sys.exit(args.func(args))
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/irods_sync.py", line 76, in handle_start
    return start_synchronization(data)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/sync_task.py", line 564, in start_synchronization
    sync_irods.validate_target_collection(data_copy, logger)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/sync_irods.py", line 23, in validate_target_collection
    if not session.collections.exists('/'):
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/manager/collection_manager.py", line 76, in exists
    self.get(path)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/manager/collection_manager.py", line 15, in get
    query = self.sess.query(Collection).filter(Collection.name == path)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/session.py", line 106, in query
    return Query(self, *args)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/query.py", line 44, in __init__
    if self.sess.server_version >= col.min_version:
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/session.py", line 130, in server_version
    conn = self.pool.get_connection()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/pool.py", line 55, in get_connection
    conn = Connection(self, self.account)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 47, in __init__
    self._server_version = self._connect()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 259, in _connect
    self.ssl_startup()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 163, in ssl_startup
    wrapped_socket = context.wrap_socket(self.socket, server_hostname=host)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Exception ignored in: <bound method Connection.__del__ of <irods.connection.Connection object at 0x7f088aadf0b8>>
Traceback (most recent call last):
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 73, in __del__
    self.disconnect()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 265, in disconnect
    self.send(disconnect_msg)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 88, in send
    raise NetworkException("Unable to send message")
irods.exception.NetworkException: Unable to send message
```

Hotfix by changing `irods/connection.py`

```
155         # Get or create SSL context
156         #try:
157         #    context = self.account.ssl_context
158         #except AttributeError:
159         CA_file = getattr(self.account, 'ssl_ca_certificate_file', None)
160         context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH, cafile=CA_file)

```

**Comment by d-w-moore** [comment]
hi Manuel,

   The recent releases (0.8.4 and 0.8.5) of the python irodsclient have been tested and found  to work with automated ingest, but possibly not  under all types of operating (especially load) conditions and there've admittedly been changes to the connection pool since 0.8.3 .  Which release of the irods client are you using?  This command line should tell you :

  python -c 'import irods ; print( irods.__version__ )'


Daniel Moore
Applications Engineer
iRODS Consortium, RENCI, UNC Chapel Hill
(919) 445-9616

________________________________

**Comment by holtgrewe** [comment]
```
python -c 'import irods ; print( irods.__version__ )'
0.8.5
```

I think the problem occurs for certificates with a custom self-signed CA. I'm specifying both `irods_ssl_ca_certificate_file` and `irods_ssl_certificate_chain_file` in the environment JSON file.

On first glance it looks like the ssl context is initialized lazily so no exception is thrown by `context = self.account.ssl_context` but instead later as shown in my exception trace. IOW: the code does not correctly test whether an SSH connection can be opened and I have to unconditionally run lines 159 and 160.

**Comment by d-w-moore** [comment]
Interesting ... Well, I see no driving need for it to remain a lazy determination. If I'm properly understanding the purpose of an SSL context and the details of the protocol, the context and the cert details should be something we can set up "for good" at session initialization, never to change for the duration of the session. 

I'll work on that, and on reproducing the problem here. (Let me know if there are any special details of your setup that might influence my success in reproducing,   either commenting it here or sending to support@irods.org if necessary for anonymity). Thanks Manuel.

**Comment by holtgrewe** [comment]
@d-w-moore I don't think my setup is very special. I don't create self-signed certificates for irods but instead create a self-signed root certificate which I'm then using to sign the icat/resource server certificates. I then place the certificates and keys of the icat/resource servers on these servers plus the CA certificate. I place the CA certificate but not the icat/resource server certificates on the clients and make the CA certificate known to the client via config. The clients can use the irods icommands without problem. The problem is with the python library only.

**Comment by d-w-moore** [comment]
Manuel, good information, thank you - I shall  reproduce and look at it today

**Comment by trel** [comment]
Fixed - thanks @d-w-moore
