### ISSUE TITLE
Exception ignored upon iRODSSession cleanup

### ISSUE THREAD

**Issue by tsmeele** [irods/python-irodsclient#315]
Context: python_irodsclient version 1.0.0    python 3.6  (also reproducable under Python2)
Preconditions:   ~/.irods/irods_environment.json file exists yet  ~/.irods/.irodsA file is missing

```
irods_env_file = os.path.expanduser(IRODS_ENV_PATH)
try:
    with open(irods_env_file, 'rt') as f:
        pass
except IOError:
    print('Error: missing iRODS environment')
    exit(1)

ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)
ssl_settings = {'ssl_context': ssl_context}

try:
    session = iRODSSession(irods_env_file=irods_env_file, **ssl_settings)
except:
    print('Sorry, could not connect to iRODS')
    exit(1)
```

Expected: clean exit
Got: ignored Exception
Impact: limited, without iRODS session not much can be done ;)

```
Sorry, could not connect to iRODS
Exception ignored in: <bound method iRODSSession.__del__ of <irods.session.iRODSSession object at 0x7f74e522d630>>
Traceback (most recent call last):
  File "/home/tsmeele/.local/lib/python3.6/site-packages/irods/session.py", line 49, in __del__
    self.cleanup()
  File "/home/tsmeele/.local/lib/python3.6/site-packages/irods/session.py", line 52, in cleanup
    for conn in self.pool.active | self.pool.idle:
AttributeError: 'NoneType' object has no attribute 'active'
```

**Comment by d-w-moore** [comment]
Yes, I see it ... we need a check for the pool object being `None` to detect the yet-unused session status in the `__del__` method , and the cleanup ( ) method can be skipped in that case.
```diff
     def __del__(self):
         self.do_configure = {}
-        self.cleanup()
+        if self.pool is not None:
+            self.cleanup()

```

**Comment by d-w-moore** [comment]
@tsmeele Let us know if this pull request satisfies your needs! :)  Meanwhile I'll put it through general test as well as writing one or two extra tests around it.

**Comment by trel** [comment]
@d-w-moore you've left a comment here on the issue, rather than a PR.    Which PR are you referencing?

**Comment by d-w-moore** [comment]
oops, will correct.
I wondered where it went... now I know!

**Comment by tsmeele** [comment]
PR prevents the ignored Exception, so that's good news.  However, the mssing .irodsA file raises a KeyError (example output below) instead of the intended NonAnonymousLoginWithoutPassword exception.
```
  File "/home/tsmeele/IrodsStore.py", line 29, in __init__
    self.connect()
  File "/home/tsmeele/IrodsStore.py", line 44, in connect
    self.session = iRODSSession(irods_env_file=self.irods_env_file, **ssl_settings)
  File "/home/tsmeele/.local/lib/python3.6/site-packages/irods/session.py", line 33, in __init__
    self.__configured = self.configure(**kwargs)
  File "/home/tsmeele/.local/lib/python3.6/site-packages/irods/session.py", line 119, in configure
    account = self._configure_account(**kwargs)
  File "/home/tsmeele/.local/lib/python3.6/site-packages/irods/session.py", line 111, in _configure_account
    if not pw and creds['user'] != 'anonymous':
KeyError: 'user'
```

**Comment by tsmeele** [comment]
suggested fix: change key 'user' to 'irods_user_name' in line 111 as it references a key from the irods_env_file
