### ISSUE TITLE
Multiple exceptions during put() when irods_path includes "'"

### ISSUE THREAD

**Issue by anderbubble** [irods/python-irodsclient#321]
Tracebacks:

```
Traceback (most recent call last):
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/connection.py", line 103, in recv
    err_msg = iRODSMessage(msg=msg.error).get_main_message(Error).RErrMsg_PI[0].msg
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/message/__init__.py", line 192, in get_main_message
    msg.unpack(ET.fromstring(self.msg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "irods-client-test.py", line 10, in <module>
    session.data_objects.put(__file__, "/civilfritz.net/home/janderson/test'ing.py")
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/manager/data_object_manager.py", line 124, in put
    o.write(chunk)
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/data_object.py", line 166, in close
    self.conn.close_file(self.desc, **self.options)
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/connection.py", line 571, in close_file
    self.recv()
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/connection.py", line 105, in recv
    raise get_exception_by_code(msg.int_info)
irods.exception.CAT_NO_ROWS_FOUND: None
```

Sample code (with redactions):

```
import irods.session

with irods.session.iRODSSession(
    host=[redacted],
    port=1247,
    user='[redacted]',
    password=[redacted],
    zone="civilfritz.net"
) as session:
    session.data_objects.put(__file__, "/civilfritz.net/home/[redacted]/test'ing.py")
```

**Comment by anderbubble** [comment]
@korydraughn let me know if you need any further info. I haven't tracked the source down myself yet, but I'll give it a bit more.

**Comment by anderbubble** [comment]
@d-w-moore looks like I tagged the wrong person initially. Sorry about that!

irods.connection.Connection.recv gets the following iRODSMessage:

```
debug: <irods.message.iRODSMessage object at 0x110d04fd0>
debug: {'msg_type': 'RODS_API_REPLY', 'msg': None, 'error': None, 'bs': None, 'int_info': -808000}
```

I tried adjusting the relevant line like this:

```
err_msg = iRODSMessage(msg=msg.error or b'').get_main_message(Error).RErrMsg_PI[0].msg
```

But then I just got a different exception.

```
Traceback (most recent call last):
  File "irods-client-test.py", line 10, in <module>
    session.data_objects.put(__file__, "/civilfritz.net/home/janderson/test'ing.py")
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/manager/data_object_manager.py", line 124, in put
    o.write(chunk)
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/data_object.py", line 166, in close
    self.conn.close_file(self.desc, **self.options)
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/connection.py", line 573, in close_file
    self.recv()
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/connection.py", line 105, in recv
    err_msg = iRODSMessage(msg=msg.error or b'').get_main_message(Error).RErrMsg_PI[0].msg
  File "/Users/janderson/Library/Python/3.8/lib/python/site-packages/python_irodsclient-1.0.0-py3.8.egg/irods/message/__init__.py", line 192, in get_main_message
    msg.unpack(ET.fromstring(self.msg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Comment by d-w-moore** [comment]
@anderbubble What is the iRODS server version? It appears to me the same problem exists with the icommand **iput**  on 4.2.9 and 4.2.10:
```
daniel@precision-5530:~$ iput "abc'" 
remote addresses: 127.0.0.1 ERROR: putUtil: put error for /tempZone/home/rods/abc', status = -808000 status = -808000 CAT_NO_ROWS_FOUND
daniel@precision-5530:~$ echo $?
3
```
It does appear to have been fixed in iRODS 4.2.11 however.

**Comment by trel** [comment]
Note, 4.2.11 isn't released yet...

We'll track down a specific commit that fixed this...

**Comment by d-w-moore** [comment]
Yep, sorry. Jumped the gun.

**Comment by alanking** [comment]
This is related to irods/irods#5759. GenQuery fails to parse the apostrophe correctly and so it cannot fetch the information from the catalog in 4.2.9 and 4.2.10. The extra query is now avoided in open which is why it is fixed in server version 4.2.11.

**Comment by trel** [comment]
Nice - closing as 'fixed'.

**Comment by anderbubble** [comment]
Thanks, @d-w-moore and @alanking. I don't know why I didn't try iput myself.

Confirmed, I'm running 4.2.10. I'll look forward to the release of 4.2.11.
