### ISSUE TITLE
Trailing slash in path gives python irods error while the same path works using icommands

### ISSUE THREAD

**Issue by RubenGarcia** [irods/python-irodsclient#323]
Tested using https://github.com/lexis-project/python-irodsclient/tree/openid_20210628.
Can you reproduce?
```
coll1 = "/LRZLexisZone/home/rods/test"
coll2 = "/LRZLexisZone/home/rods/test/"

irods_col1 = session.collections.get(coll1)
print(irods_col1.name)
irods_col2 = session.collections.get(coll2)
```
gives this when processing session.collections.get(coll2)
```
Traceback (most recent call last):
  File "/home/di76gum/.local/lib/python3.5/site-packages/irods/manager/collection_manager.py", line 17, in get
    result = query.one()
  File "/home/di76gum/.local/lib/python3.5/site-packages/irods/query.py", line 224, in one
    raise NoResultFound()
irods.exception.NoResultFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_slash.py", line 11, in <module>
    irods_col2 = session.collections.get(coll2)
  File "/home/di76gum/.local/lib/python3.5/site-packages/irods/manager/collection_manager.py", line 19, in get
    raise CollectionDoesNotExist()
irods.exception.CollectionDoesNotExist
```
The issue is triggered by the extra trailing slash.
Icommands work:
```
~$ ils /LRZLexisZone/home/rods/test/
/LRZLexisZone/home/rods/test:
  100MB.bin
  testfile2.txt
  C- /LRZLexisZone/home/rods/test/test
~$ ils /LRZLexisZone/home/rods/test
/LRZLexisZone/home/rods/test:
  100MB.bin
  testfile2.txt
  C- /LRZLexisZone/home/rods/test/test
```

**Comment by trel** [comment]
reproduced with 1.0.0

```
>>> from irods.session import iRODSSession
>>> with iRODSSession(host='localhost', port=1247, user='rods', password='rods', zone='tempZone') as session:
...   thecoll = session.collections.get('/tempZone/home/rods')
...   print(thecoll.name)
... 
rods
>>> with iRODSSession(host='localhost', port=1247, user='rods', password='rods', zone='tempZone') as session:
...   thecoll = session.collections.get('/tempZone/home/rods/')
...   print(thecoll.name)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/tgr/venv/local/lib/python2.7/site-packages/irods/manager/collection_manager.py", line 19, in get
    raise CollectionDoesNotExist()
irods.exception.CollectionDoesNotExist
```

**Comment by d-w-moore** [comment]
Agreed, we just need to strip off final '/' (unless it's the only thing in the name. session.collections.get('/') should still work.)

**Comment by korydraughn** [comment]
what API is this hitting on the server?

seems the server shouldn't be tripped up by this. the server strips trailing slashes for some APIs today.

**Comment by d-w-moore** [comment]
@korydraughn It's the genquery API

**Comment by trel** [comment]
seems the way to avoid the most tripping hazards could be...
 - strip any trailing `/`s, then
 - if empty string... add one back.

**Comment by korydraughn** [comment]
i see. it makes more sense for the PRC to strip trailing clashes.
