### ISSUE TITLE
anonymous cannot access APIs if logged in without environment

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#350]
If the anonymous user is created, we should be able to run:
```
from __future__ import print_function
import irods.session;s=irods.session.iRODSSession(user='anonymous',zone='tempZone',port=1247,host='localhost')
from irods.models import User
q = s.query(User.name).filter(User.name == 'anonymous')
print(
  list(q)[0][User.name]
)

```
and this should print out 'anonymous' at the console.

However, instead, we get:
```
python *v2.py
Traceback (most recent call last):
  File "/home/daniel/python-irodsclient/irods/pool.py", line 59, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anon_noenv2.py", line 6, in <module>
    list(q)[0][User.name]
  File "/home/daniel/python-irodsclient/irods/query.py", line 212, in get_results
    for result_set in self.get_batches():
  File "/home/daniel/python-irodsclient/irods/query.py", line 195, in get_batches
    result_set = self.execute()
  File "/home/daniel/python-irodsclient/irods/query.py", line 166, in execute
    with self.sess.pool.get_connection() as conn:
  File "/home/daniel/python-irodsclient/irods/pool.py", line 15, in method_
    ret = method(self,*s,**kw)
  File "/home/daniel/python-irodsclient/irods/pool.py", line 71, in get_connection
    conn = Connection(self, self.account)
  File "/home/daniel/python-irodsclient/irods/connection.py", line 62, in __init__
    self._login_native()
  File "/home/daniel/python-irodsclient/irods/connection.py", line 518, in _login_native
    "%ds" % MAX_PASSWORD_LENGTH, password.encode(
AttributeError: 'NoneType' object has no attribute 'encode'
python *v2.py
Traceback (most recent call last):
  File "/home/daniel/python-irodsclient/irods/pool.py", line 59, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anon_noenv2.py", line 6, in <module>
    list(q)[0][User.name]
  File "/home/daniel/python-irodsclient/irods/query.py", line 212, in get_results
    for result_set in self.get_batches():
  File "/home/daniel/python-irodsclient/irods/query.py", line 195, in get_batches
    result_set = self.execute()
  File "/home/daniel/python-irodsclient/irods/query.py", line 166, in execute
    with self.sess.pool.get_connection() as conn:
  File "/home/daniel/python-irodsclient/irods/pool.py", line 15, in method_
    ret = method(self,*s,**kw)
  File "/home/daniel/python-irodsclient/irods/pool.py", line 71, in get_connection
    conn = Connection(self, self.account)
  File "/home/daniel/python-irodsclient/irods/connection.py", line 62, in __init__
    self._login_native()
  File "/home/daniel/python-irodsclient/irods/connection.py", line 518, in _login_native
    "%ds" % MAX_PASSWORD_LENGTH, password.encode(
AttributeError: 'NoneType' object has no attribute 'encode'

```

**Comment by trel** [comment]
can anonymous run that query via iquest?

**Comment by d-w-moore** [comment]
```
daniel@precision-5530:~/python-irodsclient$ iquest "select COLL_NAME"
COLL_NAME = /tempZone/home/anonymous
------------------------------------------------------------
daniel@precision-5530:~/python-irodsclient$ 
```
Yes.  It also succeeds if logging in with the environment file....
It appears to be a little bug in `_login_native`

**Comment by trel** [comment]
I believe you, but isn't this 'more' equivalent?

`iquest "select USER_NAME where USER_NAME = 'anonymous'"`

**Comment by d-w-moore** [comment]
oops yeah sorry I started out with a collection query and the USER query had the same symptom, so I used it... my bad.  anyway, think i have a fix. submitting directly
