### ISSUE TITLE
PAM authentication failes when there is an '=' character in the password

### ISSUE THREAD

**Issue by erwinvanwieringen** [irods/python-irodsclient#362]
Trying to log in using authentication_scheme='pam' fails when there is an = character in the password. The rodsLog shows:
```
 May 12 13:38:03 pid:15641 remote addresses: 127.0.0.1, xxx.xxx.xxx.xxx ERROR: [-]	/irods_git_repo/server/api/src/rsAuthPluginRequest.cpp:86:int rsAuthPluginRequest(rsComm_t *, authPluginReqInp_t *, authPluginReqOut_t **) :  status [SYS_BAD_INPUT]  errno [] -- message [unescaped _assoc token encountered in key or value]
	[-]	/irods_git_repo/plugins/auth/pam/libpam.cpp:392:irods::error pam_auth_agent_request(irods::plugin_context &) :  status [SYS_BAD_INPUT]  errno [] -- message [unescaped _assoc token encountered in key or value]
		[-]	/irods_git_repo/lib/core/src/irods_kvp_string_parser.cpp:136:irods::error irods::parse_escaped_kvp_string(const std::string &, irods::kvp_map_t &, const std::string &, const std::string &, const std::string &) :  status [SYS_BAD_INPUT]  errno [] -- message [unescaped _assoc token encountered in key or value]
```
I think the irods API requires =-characters to be backslash-escaped. 

Maybe this can be solved in the **_login_pam** function in **connection.py** by replacing `self.account.password` by `self.account.password.replace('=', '\\=')`

**Comment by d-w-moore** [comment]
Will try to reproduce and fix this week.

**Comment by d-w-moore** [comment]
@erwinvanwieringen I've not been able to reproduce this yet.  What I have now is a PAM login for alice with password "test=124" and both iRODS and python-irodsclient seem able to perform as normal.  Are you able to give any details of your setup, including OS distribution, Python client and iRODS versions?

**Comment by erwinvanwieringen** [comment]
I'll try to create a fresh irods install and reproduce the issue there. Meanwhile, it might be the same/related to https://github.com/irods/irods/issues/3528

**Comment by erwinvanwieringen** [comment]
No my irods server is 4.2.8. I'm running on RHEL7. 

This is **/etc/pam.d/irods**
```
auth        required      pam_env.so
auth        sufficient    pam_unix.so
auth        required      pam_deny.so
```

I created a local user called **testuser1** with password **test=123**

Python code to test:
```
import ssl
from irods.session import iRODSSession

context = ssl._create_unverified_context(
    purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None
)

ssl_settings = {
    'client_server_negotiation': 'request_server_negotiation',
    'client_server_policy': 'CS_NEG_REQUIRE',
    'encryption_algorithm': 'AES-256-CBC',
    'encryption_key_size': 32,
    'encryption_num_hash_rounds': 16,
    'encryption_salt_size': 8,
    'irods_ssl_ca_certificate_file': '/etc/irods/ssl/test2/irods.crt',
    'ssl_context': context
}

irods_session = iRODSSession(
    host='<undisclosed_hostname>',
    port=1247,
    user='testuser1',
    password='test=123',
    zone='rivmZone_test_02',
    authentication_scheme='pam',
    **ssl_settings
)

print(irods_session.collections.get('/'))

irods_session.cleanup()
```

This results in the following error:
```
Traceback (most recent call last):
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/session.py", line 162, in server_version
    conn = next(iter(self.pool.active))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/pool.py", line 59, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wierinve/projects/bio-ansible/../test/test_password.py", line 29, in <module>
    print(irods_session.collections.get('/'))
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/manager/collection_manager.py", line 21, in get
    query = self.sess.query(Collection).filter(*filters)
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/session.py", line 141, in query
    return Query(self, *args)
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/query.py", line 44, in __init__
    if self.sess.server_version >= col.min_version:
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/session.py", line 165, in server_version
    conn = self.pool.get_connection()
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/pool.py", line 15, in method_
    ret = method(self,*s,**kw)
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/pool.py", line 75, in get_connection
    conn = Connection(self, self.account)
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/connection.py", line 69, in __init__
    self._login_pam()
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/connection.py", line 460, in _login_pam
    output_message = self.recv()
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/connection.py", line 128, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
  File "/mnt/scratch_dir/wierinve/conda/envs/irods_python/lib/python3.10/site-packages/irods/exception.py", line 107, in get_exception_by_code
    exc_class = iRODSExceptionMeta.codes[ rounded_code( code ) ]
KeyError: -158000
```

And in the rodsLog:
```
May 18 14:04:23 pid:34813 remote addresses: 127.0.0.1, xxx.xxx.xxx.xxx ERROR: [-]	/irods_git_repo/server/api/src/rsAuthPluginRequest.cpp:86:int rsAuthPluginRequest(rsComm_t *, authPluginReqInp_t *, authPluginReqOut_t **) :  status [SYS_BAD_INPUT]  errno [] -- message [unescaped _assoc token encountered in key or value]
	[-]	/irods_git_repo/plugins/auth/pam/libpam.cpp:392:irods::error pam_auth_agent_request(irods::plugin_context &) :  status [SYS_BAD_INPUT]  errno [] -- message [unescaped _assoc token encountered in key or value]
		[-]	/irods_git_repo/lib/core/src/irods_kvp_string_parser.cpp:136:irods::error irods::parse_escaped_kvp_string(const std::string &, irods::kvp_map_t &, const std::string &, const std::string &, const std::string &) :  status [SYS_BAD_INPUT]  errno [] -- message [unescaped _assoc token encountered in key or value]
```

When i replace the password by **test\\=123**, the program finishes sucessfully.

**Comment by trel** [comment]
okay, so either we have a bug, or the iRODSSession needs to do a little more work for you - no reason for the user to have to know this silliness.

**Comment by lwesterhof** [comment]
We have also encountered this issue, also with @, & and ;. As a workaround we escape them before sending it to our PAM stack: https://github.com/UtrechtUniversity/yoda-portal/blob/923a7014252070587fba02d530a2bb9a41e39900/user/user.py#L366

**Comment by alanking** [comment]
A complete solution is provided through changes for #522.

**Comment by trel** [comment]
add this to 2.0.1?

**Comment by trel** [comment]
thought this was just closed.   ignore me.
