### ISSUE TITLE
noisy socket exit message

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#368]
If we run he following script `demo.py` using Python3:
```
import ssl
from irods.session import iRODSSession
from irods.test.helpers import home_collection
import atexit
import socket

ssl_settings = {
    'client_server_negotiation': 'request_server_negotiation',
    'client_server_policy': 'CS_NEG_REQUIRE',
    'encryption_algorithm': 'AES-256-CBC',
    'encryption_key_size': 32,
    'encryption_num_hash_rounds': 16,
    'encryption_salt_size': 8,
    'irods_ssl_ca_certificate_file': '/etc/irods/ssl/irods.crt',
    'ssl_context': ssl._create_unverified_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)
}

hn = socket.gethostname()

irods_session = iRODSSession(
    host=hn,
    port=1247,
    user='alice',
    password='apass',
    zone='tempZone',
    **ssl_settings
)

if __name__ == '__main__':
# atexit.register(lambda : irods_session.cleanup())
  h = home_collection(irods_session)
  print(irods_session.collections.get(h).path, 'in __main__')
```

in Python3 we see in the output extra lines arising from the Python runtime's shutdown stage:
```
$ python3 demo.py
/tempZone/home/alice in __main__
Exception ignored in: <bound method Connection.__del__ of <irods.connection.Connection object at 0x7faaad0d44a8>>
Traceback (most recent call last):
  File "/home/daniel/python-irodsclient/irods/connection.py", line 89, in __del__
  File "/home/daniel/python-irodsclient/irods/connection.py", line 295, in disconnect
  File "/home/daniel/python-irodsclient/irods/connection.py", line 105, in send
irods.exception.NetworkException: Unable to send message
```
Uncommenting the `atexit.register(...)` line will prevent the traceback, so it's pretty sure that the "orderly" shutdown and destruction of Python objects isn't proceeding so as to destruct PRC objects in the way (or order?) we might desire.

**Comment by d-w-moore** [comment]
Python2 doesn't produce the messy stuff because its runtime is not as vigilant in terms of performing garbage collection as a part of shutdown.
