### ISSUE TITLE
acls.get fails for collection after removing user 

### ISSUE THREAD

**Issue by ReinV** [irods/python-irodsclient#431]
Hi!

session.acls.get fails for a collection if a user that had acces to that specific collection is removed. sessioin.permissions.get still works though, so that makes me think it is not expected behaviour. 

```
# imports
from irods.session import iRODSSession
from irods.access import iRODSAccess
import ssl 

# create session
ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH)
ssl_settings = {'ssl_context': ssl_context}
session = iRODSSession(host="localhost", user="rods", password="rods", port=1247, zone="tempZone", **ssl_settings)

# create user and collection
user_name = "testuser"
user = session.users.create(user_name, 'rodsuser')
coll_path = "/{0.zone}/home/test".format(session)
coll = session.collections.create(coll_path)

# give user acces to collection
acces = iRODSAccess('read', coll.path, user.name)
session.acls.set(acces)

# we can get permissions from collection
perms = session.acls.get(coll)

# now we remove the user and try again
user.remove()
perms = session.acls.get(coll)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adm-irods1/.conda/envs/ingest/lib/python3.10/site-packages/irods/session.py", line 78, in get
    return super(ACLs,self).get(target, report_raw_acls = True, **kw)
  File "/home/adm-irods1/.conda/envs/ingest/lib/python3.10/site-packages/irods/manager/access_manager.py", line 42, in get
    return self.__get_raw(target, **kw)  # prefer a behavior consistent  with 'ils -A`
  File "/home/adm-irods1/.conda/envs/ingest/lib/python3.10/site-packages/irods/manager/access_manager.py", line 118, in __get_raw
    acls = [ iRODSAccess ( r[access_column.name],
  File "/home/adm-irods1/.conda/envs/ingest/lib/python3.10/site-packages/irods/manager/access_manager.py", line 120, in <listcomp>
    user_lookup[r[access_column.user_id]].name,
KeyError: 10020

# but doesn't fail with permissions.get
perms = session.permissions.get(coll)
```

Also fails in the same way if you session.collections.get the collection object again after removing the users. 

Best, Rein

**Comment by d-w-moore** [comment]
@ReinV - We're considering this [possible fix](https://github.com/irods/python-irodsclient/pull/432) though the "real' fix probably depends on resolution of https://github.com/irods/irods/issues/6921

**Comment by ReinV** [comment]
Ok, thanks for the update. To me it's not an urgent matter, also because permissions does the same (for now).

**Comment by d-w-moore** [comment]
@ReinV - yes `permissions` will work fine as long as `report_raw_acls`  defaults to `False`
