### ISSUE TITLE
PAM login fails on Windows

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#433]
Client-end OS: Windows 10 Enterprise
PRC: v1.1.6
iRODS version: 4.2.11 as released

Attempting to use this script (pamlogin.py) to log in using PAM authentication from a Windows 10 client:
```
import sys
from irods.session import iRODSSession
import ssl

ssl_settings =  {
               "authentication_scheme": "PAM",
               "client_server_negotiation": "request_server_negotiation",
               "client_server_policy": "CS_NEG_REQUIRE",
               "encryption_key_size": 32,
               "encryption_salt_size": 8,
               "encryption_num_hash_rounds": 16,
               "encryption_algorithm": "AES-256-CBC",
               "ssl_verify_server": "none",
}

USER='alice'
PASS='apassw'

with iRODSSession(host='pam-enabled-server', port=1247, user=USER, password=PASS, zone='tempZone', **ssl_settings) as session:
    coll = session.collections.get('/tempZone/home/alice')
    print(coll)
    print(coll.path)
    print(coll.id)
    print(coll.name)
    print(coll.metadata.items())
```

we fail to connect, getting this error dump from the client:
```

Traceback (most recent call last):
  File "c:\users\unc support\python-irodsclient\irods\session.py", line 215, in server_version
    return tuple(ast.literal_eval(reported_vsn))
  File "C:\Users\UNC Support\AppData\Local\Programs\Python\Python310\lib\ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "C:\Users\UNC Support\AppData\Local\Programs\Python\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 0

SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\unc support\python-irodsclient\irods\session.py", line 221, in __server_version
    conn = next(iter(self.pool.active))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\unc support\python-irodsclient\irods\pool.py", line 59, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\unc support\python-irodsclient\irods\connection.py", line 224, in _connect
    s = socket.create_connection(address, timeout)
  File "C:\Users\UNC Support\AppData\Local\Programs\Python\Python310\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\UNC Support\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UNC Support\pamlogin.py", line 20, in <module>
    coll = session.collections.get('/tempZone/home/alice')
  File "c:\users\unc support\python-irodsclient\irods\manager\collection_manager.py", line 21, in get
    query = self.sess.query(Collection).filter(*filters)
  File "c:\users\unc support\python-irodsclient\irods\session.py", line 193, in query
    return Query(self, *args)
  File "c:\users\unc support\python-irodsclient\irods\query.py", line 44, in __init__
    if self.sess.server_version >= col.min_version:
  File "c:\users\unc support\python-irodsclient\irods\session.py", line 217, in server_version
    return self.__server_version()
  File "c:\users\unc support\python-irodsclient\irods\session.py", line 224, in __server_version
    conn = self.pool.get_connection()
  File "c:\users\unc support\python-irodsclient\irods\pool.py", line 15, in method_
    ret = method(self,*s,**kw)
  File "c:\users\unc support\python-irodsclient\irods\pool.py", line 75, in get_connection
    conn = Connection(self, self.account)
  File "c:\users\unc support\python-irodsclient\irods\connection.py", line 74, in __init__
    self._login_pam()
  File "c:\users\unc support\python-irodsclient\irods\connection.py", line 485, in _login_pam
    self._connect()
  File "c:\users\unc support\python-irodsclient\irods\connection.py", line 227, in _connect
    raise NetworkException(
irods.exception.NetworkException: Could not connect to specified host and port: prec3431:1247
```

**Comment by d-w-moore** [comment]
Another piece of the puzzle:  By commenting out  the `"authentication_scheme": "PAM",` line and changing USER/PASS to a valid combination for a natively authenticated user eg. rods, we find that SSL *does* work from Windows 10 , allowing the login and the desired output:
```
<iRODSCollection 10025 b'alice'>
/tempZone/home/alice
10025
alice
[]
```

**Comment by d-w-moore** [comment]
Yet another data point here, one that demonstrates with a simpler connect call.
Also, the results are nondeterministic, and sometimes this script succeeds in the connect, sometimes not!

```
# pamconn.py

import sys
from irods.session import iRODSSession
import ssl
import os
import time

ssl_settings =  {
               "authentication_scheme": "PAM",
               "client_server_negotiation": "request_server_negotiation",
               "client_server_policy": "CS_NEG_REQUIRE",
               "encryption_key_size": 32,
               "encryption_salt_size": 8,
               "encryption_num_hash_rounds": 16,
               "encryption_algorithm": "AES-256-CBC",
               "ssl_verify_server": "none",
}

USER='alice'
PASS='apassw'

with iRODSSession(host='prec3431', port=1247, user=USER, password=PASS, zone='tempZone', **ssl_settings) as session:
  conn = session.pool.get_connection() 
```

When it does fail, the console message is as follows:

```
>python pamconn.py
Traceback (most recent call last):
  File "c:\users\unc support\python-irodsclient\irods\pool.py", line 59, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\unc support\python-irodsclient\irods\connection.py", line 224, in _connect
    s = socket.create_connection(address, timeout)
  File "C:\Users\UNC Support\AppData\Local\Programs\Python\Python310\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\UNC Support\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UNC Support\pamconn.py", line 28, in <module>
    conn = session.pool.get_connection()
  File "c:\users\unc support\python-irodsclient\irods\pool.py", line 15, in method_
    ret = method(self,*s,**kw)
  File "c:\users\unc support\python-irodsclient\irods\pool.py", line 75, in get_connection
    conn = Connection(self, self.account)
  File "c:\users\unc support\python-irodsclient\irods\connection.py", line 74, in __init__
    self._login_pam()
  File "c:\users\unc support\python-irodsclient\irods\connection.py", line 486, in _login_pam
    self._connect()
  File "c:\users\unc support\python-irodsclient\irods\connection.py", line 227, in _connect
    raise NetworkException(
irods.exception.NetworkException: Could not connect to specified host and port: prec3431:1247
```

**Comment by d-w-moore** [comment]
Tried the code in the description (on PRC v3.2.0 , Windows 10, and iRODS 4.3.4 on a remote host) and was unable to duplicate the issue.  Since at the time of reporting, only the the old PAM login code path existed , I used the setting : `irods.client_configuration.legacy_auth.force_legacy_auth = True`

I've  verified, also, that on Windows we're able to create an .irodsA pam_password authfile under Windows and then login normally (instantiate a functional irods session) using the resulting .irodsA.  I tried both with and without `force_legacy_auth` being set True, 

So I'd say we would be best closing this issue for now.

**Comment by d-w-moore** [comment]
There's a specific test but it runs on docker. The image is Ubuntu.

**Comment by korydraughn** [comment]
Based on the conversation, this issue is now about enabling automated testing for Windows.

Updating labels and milestone.
