### ISSUE TITLE
Can't add 0 as value in metadata.set()

### ISSUE THREAD

**Issue by jefscheepers** [irods/python-irodsclient#434]
One of our users discovered that it isn't possible to add the integer 0 as metadata via the Python client without converting it to a string first.

When we use  _coll.metadata.set("number", 0, None)_ , the script hangs and eventually crashes with the following errors:

```
Traceback (most recent call last):
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/message/__init__.py", line 180, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/ssl.py", line 1055, in recv
    self.__class__)
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/connection.py", line 114, in recv
    msg = iRODSMessage.recv(self.socket)
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/message/__init__.py", line 270, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/message/__init__.py", line 182, in _recv_message_in_len
    buf = sock.recv(size_left)
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/ssl.py", line 1056, in recv
    return self.read(buflen)
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/ssl.py", line 931, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_integer_metadata.py", line 13, in <module>
    coll.metadata.set("number", 0, None)
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/meta.py", line 129, in set
    self._manager.set(self._model_cls, self._path, meta, **opts)
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/manager/metadata_manager.py", line 171, in set
    response = conn.recv()
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/connection.py", line 125, in recv
    raise NetworkException("Could not receive server response")
irods.exception.NetworkException: Could not receive server response
Exception ignored in: <function Connection.__del__ at 0x7f651fc554d0>
Traceback (most recent call last):
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/connection.py", line 90, in __del__
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/connection.py", line 303, in disconnect
  File "/home/jef/miniconda3/envs/irods_training/lib/python3.7/site-packages/irods/connection.py", line 106, in send
irods.exception.NetworkException: Unable to send message
```

This can be solved by transforming 0 to a string first:
 _coll.metadata.set("number", 0, None)_

What's strange, is that this only needed for the number 0.
Other numbers (1,2,...) work fine without being transformed into a string first. 

All mentioned above works the same for data objects. 

Since this behavior seemed inconsistent, we wanted to mention it.
My apologies if this is due to reasons outside of the Python-irodsclient. 

Tested with python-irodsclient 1.1.6 and Python 3.7.

**Comment by d-w-moore** [comment]
@jefscheepers - Correct, the AVU value fields are strings, as are the attributes and units fields.  PostgreSQL, for example, stores the value field as `character varying(2700)`.  

As a general practice, I'd recommend always converting data you want to store there into a string first.  

And, though I wouldn't always claim this restriction always to be a "welcome feature",  it can sometimes be used to an advantage in a dynamic language such as Python. For example - the format of the stored value string  could hint at  the desired type upon being unpacked:
```
>>> for k,v in zip('wxyz',(0, 0.0, 1j,"string")): c.metadata.set(*map(repr,(k,v)))
... 
>>> c.metadata.items()
[<iRODSMeta 10055 'w' 0 None>, <iRODSMeta 10056 'x' 0.0 None>, <iRODSMeta 10057 'y' 1j None>, <iRODSMeta 10058 'z' 'string' None>]
>>> for a,v,u in ((m.name,m.value,m.units) for m in c.metadata.items()):
...  v = ast.literal_eval(v)
...  print ("Attr:{}\nValue and type:{} {}\nUnit:{}\n---".format(a,v,type(v),u))
... 
Attr:'w'
Value and type:0 <class 'int'>
Unit:None
---
Attr:'x'
Value and type:0.0 <class 'float'>
Unit:None
---
Attr:'y'
Value and type:1j <class 'complex'>
Unit:None
---
Attr:'z'
Value and type:string <class 'str'>
Unit:None
---

```

**Comment by d-w-moore** [comment]
All the same, it is weird that the AVU set would accept the integer 1 as a value , but not an integer 0, so I'll look into it.

**Comment by d-w-moore** [comment]
@jefscheepers I know it probably isn't what you pictured , but we've standardized on this plan, I think : all AVU fields must be of type str or bytes or None in the units field).  You might be able to subclass iRODSMeta itself, however,  if you are still interested in  smoother facility for interconversion of types.

Closing this issue presently, but please reopen if you need to discuss further....

**Comment by jefscheepers** [comment]
@d-w-moore I'm not against this approach, since at least it's consistent. Thanks  for looking into this.

**Comment by d-w-moore** [comment]
@jefscheepers - The team ultimately though that making the conversion explicit - with the application programmer calling str( ), repr( ) or other choice of a string conversion -  would be preferable to letting the string translation be handled by the library.
