### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MSG_WAITALL'

### ISSUE THREAD

**Issue by donpellegrino** [irods/python-irodsclient#53]
When attempting the examples in README.md, an "AttributeError: 'module' object has no attribute 'MSG_WAITALL'" is generated.

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    coll = sess.collections.get('/TestZone01/projects')
  File "C:\Python27\lib\site-packages\irods\manager\collection_manager.py", line 15, in get
    result = query.one()
  File "C:\Python27\lib\site-packages\irods\query.py", line 217, in one
    results = self.execute()
  File "C:\Python27\lib\site-packages\irods\query.py", line 169, in execute
    with self.sess.pool.get_connection() as conn:
  File "C:\Python27\lib\site-packages\irods\pool.py", line 22, in get_connection
    conn = Connection(self, self.account)
  File "C:\Python27\lib\site-packages\irods\connection.py", line 22, in __init__
    self._server_version = self._connect()
  File "C:\Python27\lib\site-packages\irods\connection.py", line 82, in _connect
    version_msg = self.recv()
  File "C:\Python27\lib\site-packages\irods\connection.py", line 41, in recv
    msg = iRODSMessage.recv(self.socket)
  File "C:\Python27\lib\site-packages\irods\message\__init__.py", line 41, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "C:\Python27\lib\site-packages\irods\message\__init__.py", line 19, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
AttributeError: 'module' object has no attribute 'MSG_WAITALL'
```

**Comment by adetorcy** [comment]
Is this the same issue as iPlantCollaborativeOpenSource/python-irodsclient/issues/10?

**Comment by donpellegrino** [comment]
Yes, this looks like the same issue.

**Comment by adetorcy** [comment]
The workaround (keep receiving data from socket until a given length has been read) looks like what [_recv_message_in_len(sock, size)](../blob/master/irods/message/__init__.py#L15) is already doing, so you might not need the MSG_WAITALL flag here.
In your file C:\Python27\lib\site-packages\irods\message\__init__.py, line 19 please replace
`buf = sock.recv(size_left, socket.MSG_WAITALL)`
with
`buf = sock.recv(size_left)`
Is that helping?

**Comment by donpellegrino** [comment]
That change to line 19 resolves the issue. Thanks!

If MSG_WAITALL is doing something useful on non-Windows platforms perhaps a conditional to not apply it on Windows work would in the code.
