### ISSUE TITLE
Can i use "iRODSSession.data_objects.open()" to read/write binary files?

### ISSUE THREAD

**Issue by LeeJH** [irods/python-irodsclient#69]
Can i use "iRODSSession.data_objects.open()" to read/write binary files?

**Comment by adetorcy** [comment]
Yes. iRODS data objects are treated as binary data. Are you getting unexpected results?

**Comment by LeeJH** [comment]
I got an error when i was trying to upload a figure as following:
>>> obj3=sess.data_objects.create("/myZone/home/rods/3.jpg")
>>> fobj3=obj3.open("w")
>>> finp=open("/HOME/username/1.jpg","rb")
>>> fobj3.write(finp.read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/bin/Python/2.7.9-fPIC/lib/python2.7/site-packages/irods/data_object.py", line 105, in write
    return self.conn.write_file(self.desc, str(b))
  File "/usr/bin/Python/2.7.9-fPIC/lib/python2.7/site-packages/irods/connection.py", line 312, in write_file
    self.send(message)
  File "/usr/bin/Python/2.7.9-fPIC/lib/python2.7/site-packages/irods/connection.py", line 47, in send
    string = message.pack()
  File "/usr/bin/Python/2.7.9-fPIC/lib/python2.7/site-packages/irods/message/__init__.py", line 82, in pack
    joined_parts = ("".join(parts)).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 216: ordinal not in range(128)

**Comment by adetorcy** [comment]
I see. Please try the patch below and let me know if this fixes your issue:

```
diff --git a/irods/message/__init__.py b/irods/message/__init__.py
index edec6ae..b9d3d55 100644
--- a/irods/message/__init__.py
+++ b/irods/message/__init__.py
@@ -79,7 +79,10 @@ class iRODSMessage(object):
         msg_header_length = struct.pack(">i", len(msg_header))
         msg_header_length = msg_header_length
         parts = [x for x in [main_msg, self.error, self.bs] if x is not None]
-        joined_parts = ("".join(parts)).encode('utf-8')
+        try:
+            joined_parts = "".join(parts).encode('utf-8')
+        except UnicodeDecodeError:
+            joined_parts = "".join(parts)
         msg_header = msg_header.encode('utf-8')
         msg = msg_header_length + msg_header + joined_parts
         return msg
```

**Comment by LeeJH** [comment]
With the fix, it is now working in my case. Thanks.

**Comment by pdonorio** [comment]
I am getting similar error with some file. 

I just found this issue so I will also try this fix, but if it works shouldn't it be merged into master?

**Comment by adetorcy** [comment]
This is just a hack. I'll have to revisit the packing function when I have a second.

**Comment by pdonorio** [comment]
Ok, I see; and the patch solve some cases. 
But with non ASCII characters the problem changes, I get:

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 64, in recv
    msg = iRODSMessage.recv(self.socket)
  File "/usr/local/lib/python3.6/dist-packages/irods/message/__init__.py", line 44, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "/usr/local/lib/python3.6/dist-packages/irods/message/__init__.py", line 21, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/data_object.py", line 105, in write
    return self.conn.write_file(self.desc, str(b))
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 313, in write_file
    response = self.recv()
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 67, in recv
    exit(1)
  File "/usr/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

During handling of the above exception, another exception occurred:

  File "/code/flask_ext/flask_irods/client.py", line 332, in save
    target.close()
  File "/usr/local/lib/python3.6/dist-packages/irods/data_object.py", line 85, in close
    self.conn.close_file(self.desc, self.options)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 347, in close_file
    self.send(message)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 60, in send
    raise NetworkException("Unable to send message")
irods.exception.NetworkException: Unable to send message
```

I'm using Python 3.6, and to make the problem appear you just have to change one of [there strings](https://github.com/irods/python-irodsclient/blob/master/irods/test/file_test.py#L17-L19) to something like:
```python
content_str = "£$%&($)/(*é:_§°:#".encode()
```

**Comment by pdonorio** [comment]
Hello, I was able to fix this problem on Python 3 with [this commit](https://github.com/pdonorio/python-irodsclient/commit/5bdd669231b9f9fce6fa62fd55033efdbf4443e5)

**Comment by adetorcy** [comment]
This latest commit aims to better support unicode in Python 2. It is untested on Python 3 so if you get the chance to try it please let me know how it goes, and whether you are still observing the above errors.

The idea here is that we want to:
- Use unicode strings as much as possible (default in Python 3), and encode/decode when packing and unpacking respectively
- Avoid calling `encode()` on a byte string (because Python 2 will implicitly decode it as ascii)
- Avoid concatenating byte and unicode strings (again because of implicit decoding in Python 2)

**Comment by pdonorio** [comment]
Ok, I will switch back from my fork to this official repo and make some tests

**Comment by pdonorio** [comment]
Does not work on Python 3.6:

```bash
  File "/usr/local/lib/python3.6/dist-packages/irods/message/__init__.py", line 73, in encode_unicode
    if type(my_str) is unicode:
NameError: name 'unicode' is not defined
```

I'll work a patch with a new fork

**Comment by pdonorio** [comment]
[Here](https://github.com/pdonorio/python-irodsclient/commit/281ef81957ce98c3eb50c9c455379d8bf0693566)'s a patch, let me know

**Comment by pdonorio** [comment]
Uhm, since your + my patch there seems to be some strange behaviour. I will try to revert back to see if those modifications made the problem exist

**Comment by adetorcy** [comment]
Thanks for helping with this. I have a fix in the works that includes your patch. Currently under testing with PY2 and PY3. Will push shortly if all tests pass

**Comment by pdonorio** [comment]
> since your + my patch there seems to be some strange behaviour

I reverted back to the end of april and it still happens. I get permission denied on objects my user own. I'll try your patch again since I have no idea where this came from.

**Comment by pdonorio** [comment]
Thanks for your Python 3 fix, it works.
You may close this issue :)

Note: I only have [this commit](https://github.com/pdonorio/python-irodsclient/commit/7186664301c5785e3e79d365c5dc67c71fa935b3) left in my fork that differs from your official repo. Cheers :beers:

**Comment by adetorcy** [comment]
Pushed. Thanks

**Comment by pdonorio** [comment]
> Pushed

Thank you too!

**Comment by muccix** [comment]
I'm experiencing the issues with binaries files: both a pdf and a jpg.
The file is uploaded to iRODS correctly but trying to get it I receive the following error:

"'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte"
