### ISSUE TITLE
Calling an Specific Query that doesn't exist on the Zone doesn't give an iRODS specific Exception

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#81]
This is what happens if you call with a incorrect stored query name
```
>>> res_q = SpecificQuery(SESS, alias="ThisQueryDoesntExist")
>>> res_q.get_results()
<generator object get_results at 0x18a43c0>
>>> for r in res_q.get_results():
...     pprint.pprint(r)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/iRODS/sanger-scripts/virtualenv_prc_0.6.0/local/lib/python2.7/site-packages/irods/query.py", line 334, in get_results
    for result_set in self.get_batches():
  File "/usr/local/iRODS/sanger-scripts/virtualenv_prc_0.6.0/local/lib/python2.7/site-packages/irods/query.py", line 321, in get_batches
    result_set = self.execute()
  File "/usr/local/iRODS/sanger-scripts/virtualenv_prc_0.6.0/local/lib/python2.7/site-packages/irods/query.py", line 314, in execute
    response = conn.recv()
  File "/usr/local/iRODS/sanger-scripts/virtualenv_prc_0.6.0/local/lib/python2.7/site-packages/irods/connection.py", line 70, in recv
    raise get_exception_by_code(msg.int_info)
  File "/usr/local/iRODS/sanger-scripts/virtualenv_prc_0.6.0/local/lib/python2.7/site-packages/irods/exception.py", line 68, in get_exception_by_code
    return iRODSExceptionMeta.codes[code]()
KeyError: -853000
```
It would be nice if it returned an proper python exception, e.g. `irods.exception.NO_SUCH_QUERY`, so it can be put into a try/except block for loading the query if it doesn't exist (We would like to write scripts that run a query, adding them if they don't already exist).

**Comment by adetorcy** [comment]
Now with the proper exception. The error message mentions `iadmin` because that's what comes back from the server. Ideally we will want iRODS to return client agnostic messages, but if needed you can re-raise the exception with your own error message.
```python 
>>> from irods.session import iRODSSession
>>> from irods.query import SpecificQuery
>>> 
>>> with iRODSSession(host='icat',
...                   port=1247,
...                   user='rods',
...                   password='*********************',
...                   zone='tempZone') as session:
...     
...     query = SpecificQuery(session, alias='ThisQueryDoesntExist')
...     for result in query.get_results():
...             pass
... 
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "irods/query.py", line 334, in get_results
    for result_set in self.get_batches():
  File "irods/query.py", line 321, in get_batches
    result_set = self.execute()
  File "irods/query.py", line 314, in execute
    response = conn.recv()
  File "irods/connection.py", line 74, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_UNKNOWN_SPECIFIC_QUERY: The SQL is not pre-defined.
  See 'iadmin h asq' (add specific query)
```

**Comment by kript** [comment]
Most likely my lack of understanding of python, but how would you expect to catch that exception?

I tried;

```
>>> query = SpecificQuery(SESS, sql, sql_alias)
>>> query.register()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/iRODS/sanger-scripts/virtualenv_python-irodsclient_cloned/local/lib/python2.7/site-packages/irods/query.py", line 271, in register
    response = conn.recv()
  File "/usr/local/iRODS/sanger-scripts/virtualenv_python-irodsclient_cloned/local/lib/python2.7/site-packages/irods/connection.py", line 74, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_INVALID_ARGUMENT: Alias is not unique
>>> try:
...     query.register()
... except CAT_INVALID_ARGUMENT:
...     print "we already got one of those"
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
NameError: name 'CAT_INVALID_ARGUMENT' is not defined
>>> try:
...     query.register()
... except irods.exception.CAT_INVALID_ARGUMENT:
...     print "we already got one of those"
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
NameError: name 'irods' is not defined
```

**Comment by adetorcy** [comment]
It's likely an `import` issue. See example below:
```python
>>> from irods.session import iRODSSession
>>> from irods.query import SpecificQuery
>>> import irods.exception as ex
>>> 
>>> with iRODSSession(host='icat',
...                   port=1247,
...                   user='rods',
...                   password='*********************************',
...                   zone='tempZone') as session:
...     
...     query = SpecificQuery(session, sql='select data_name from r_data_main', alias='list_data_names')
...     
...     try:
...             query.register()
...     except ex.CAT_INVALID_ARGUMENT as err:
...             if str(err) == 'Alias is not unique':
...                     print 'Query already exists'
...             raise
... 
Query already exists
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "irods/query.py", line 271, in register
    response = conn.recv()
  File "irods/connection.py", line 82, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_INVALID_ARGUMENT: Alias is not unique
>>> 

```

**Comment by kript** [comment]
yes, thats it;

```
>>> try:
...     query.register()
... except ex.CAT_INVALID_ARGUMENT:
...     print "we already got one of those"
... 
we already got one of those
```
