### ISSUE TITLE
query.register returns misleading exception when told to insert a query that already exists

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#82]
This is what happens when you call query.register on a existing query
```
>>> CompoundResourceTree = "root"
>>> # make specific query
... sql = "select count(*) from r_data_main where resc_name = '{}' and data_is_dirty = '0'".format(CompoundResourceTree)
>>> sql_alias = 'DirtyReplicas{}'.format(CompoundResourceTree)
>>> query = SpecificQuery(SESS, sql, sql_alias)
>>> # register query in iCAT
... query.register()
<irods.message.iRODSMessage object at 0x1face50>
>>> query.register()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/iRODS/sanger-scripts/virtualenv_python-irodsclient_0.6.0/local/lib/python2.7/site-packages/irods/query.py", line 271, in register
    response = conn.recv()
  File "/usr/local/iRODS/sanger-scripts/virtualenv_python-irodsclient_0.6.0/local/lib/python2.7/site-packages/irods/connection.py", line 70, in recv
    raise get_exception_by_code(msg.int_info)
irods.exception.CAT_INVALID_ARGUMENT
```
I would argue that `CAT_INVALID_ARGUMENT` is misleading, as it should inform the user that the query already exists, however, I'm not sure how e.g. `iadmin` handles this.

**Comment by adetorcy** [comment]
`CAT_INVALID_ARGUMENT` is the error code you get back from the server. I have added support for retrieving the error message as well, which may provide more information.
For example, when trying to register a query that already exists:
```python
>>> from irods.session import iRODSSession
>>> from irods.query import SpecificQuery
>>> 
>>> with iRODSSession(host='icat',
...                   port=1247,
...                   user='rods',
...                   password='*****************',
...                   zone='tempZone') as session:
...     
...     query = SpecificQuery(session, sql='select data_name from r_data_main', alias='list_data_names')
...     query.register()
...     query.register()
... 
<irods.message.iRODSMessage object at 0x7f146de2ef10>
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "irods/query.py", line 271, in register
    response = conn.recv()
  File "irods/connection.py", line 74, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_INVALID_ARGUMENT: Alias is not unique
>>>
```

**Comment by kript** [comment]
Thanks for this. Do you plan to release 0.6.1 to also cover #81 ? I can work around by cloning the repo for the one of scripts, but for the ones I'm rolling out across all the systems, having an up to date pip package is really helpful.

**Comment by adetorcy** [comment]
There were no immediate plans for a point release but if it's something you need I can make one, probably in the next month or so.
