### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by massimo1962** [irods/python-irodsclient#87]
I am trying to connect to iRODS server (ver 4.1.3) from a Python client PRC (ver. 0.6 - latest) with python version 3.6.1 and the connection fails with the following error:

 File "/usr/local/lib/python3.6/dist-packages/irods/message/property.py", line 74, in parse
    val = val.decode('utf-8') #
    │     └ b"\xbd<\xbf\x92\\\x18\xce\x8f\r\x1f\xa4\x97\xea\x87\xac\xf9\xb7\xc3\xc7\x17\xd8Q\x97\xd1\x10\xdfE\xcb\xb5\x0e\xb5\x8b\x01\x8d\xe...
    └ b"\xbd<\xbf\x92\\\x18\xce\x8f\r\x1f\xa4\x97\xea\x87\xac\xf9\xb7\xc3\xc7\x17\xd8Q\x97\xd1\x10\xdfE\xcb\xb5\x0e\xb5\x8b\x01\x8d\xe...
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte

could be a possible error on PRC or I have to do something else on server side?
After inserted a dectection encoding as debug ( chardet.detect(val)) in property.py line70 ) I found some 'strange' encoding detection:
{'encoding': 'TIS-620', 'confidence': 0.4029997574805031, 'language': 'Thai'}
{'encoding': None, 'confidence': 0.0, 'language': None}
{'encoding': 'windows-1253', 'confidence': 0.30831764227772374, 'language': 'Greek'}
... and so on...
many thanks in advance for your help.
Cheers

**Comment by adetorcy** [comment]
Can you post a code snippet where you are seeing this error?
If this involves accessing data, what type of data is it?

Thanks

**Comment by massimo1962** [comment]
The call is for: rpc.collections.get(path)

that is a wrapper for this " coll = sess.collections.get("/tempZone/home/rods") "

about the kind of files it is binary (actually 'MSEED' a seismological format)
from the exception printed on console seems that the connection is established..
Please, let me know if you need some other lines of code.

Many thanks.

**Comment by adetorcy** [comment]
Can you print your full error traceback? Thanks

**Comment by massimo1962** [comment]
This is the entire traceback with some debug...
Thanks

2017-07-26 14:15:54,434 [VERBOSE rapydo.flask_ext.flask_irods:53] Irods user: rods
2017-07-26 14:15:54,496 [DEBUG chardet.charsetprober:61] SHIFT_JIS Japanese prober hit error at byte 31
2017-07-26 14:15:54,496 [DEBUG chardet.charsetprober:62] EUC-JP Japanese prober hit error at byte 1
2017-07-26 14:15:54,497 [DEBUG chardet.charsetprober:66] GB2312 Chinese prober hit error at byte 9
2017-07-26 14:15:54,497 [DEBUG chardet.charsetprober:66] EUC-KR Korean prober hit error at byte 1
2017-07-26 14:15:54,497 [DEBUG chardet.charsetprober:66] CP949 Korean prober hit error at byte 1
2017-07-26 14:15:54,497 [DEBUG chardet.charsetprober:66] Big5 Chinese prober hit error at byte 2
2017-07-26 14:15:54,497 [DEBUG chardet.charsetprober:66] EUC-TW Taiwan prober hit error at byte 1
2017-07-26 14:15:54,499 [DEBUG chardet.charsetprober:100] windows-1251 Russian confidence = 0.0
2017-07-26 14:15:54,499 [DEBUG chardet.charsetprober:100] KOI8-R Russian confidence = 0.19979700125180314
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] ISO-8859-5 Russian confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] MacCyrillic Russian confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] IBM866 Russian confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] IBM855 Russian confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] ISO-8859-7 Greek confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] windows-1253 Greek confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] ISO-8859-5 Bulgairan confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] windows-1251 Bulgarian confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] TIS-620 Thai confidence = 0.0
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] ISO-8859-9 Turkish confidence = 0.16131438964684247
2017-07-26 14:15:54,500 [DEBUG chardet.charsetprober:100] windows-1255 Hebrew confidence = 0.0
2017-07-26 14:15:54,501 [DEBUG chardet.charsetprober:100] windows-1255 Hebrew confidence = 0.0
2017-07-26 14:15:54,501 [DEBUG chardet.charsetprober:100] windows-1255 Hebrew confidence = 0.0
test-MASSIMO {'encoding': None, 'confidence': 0.0, 'language': None}
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
    │        └ <function main at 0x7fce297408c8>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
    │             │               └ None
    │             └ ['run', '--host', '0.0.0.0', '--port', '5000', '--reload', '--no-debugger', '--eager-loading', '--with-threads']
    └ <flask.cli.FlaskGroup object at 0x7fce2973f128>
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
           │             │      │       └ {'args': ['run', '--host', '0.0.0.0', '--port', '5000', '--reload', '--no-debugger', '--eager-loading', '--with-threads'], 'prog...
           │             │      └ ()
           │             └ <flask.cli.FlaskGroup object at 0x7fce2973f128>
           └ <class 'flask.cli.AppGroup'>
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
         │           └ <click.core.Context object at 0x7fce2c583e48>
         └ <flask.cli.FlaskGroup object at 0x7fce2973f128>
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │                      └ <click.core.Context object at 0x7fce2c583898>
           │               └ <click.core.Context object at 0x7fce2c583898>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fce2c734ea0>
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │          │                └ <click.core.Context object at 0x7fce2c583898>
           │          └ <click.core.Command object at 0x7fce2973f0b8>
           └ <click.core.Context object at 0x7fce2c583898>
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'host': '0.0.0.0', 'port': 5000, 'reload': True, 'debugger': False, 'eager_loading': True, 'with_threads': True}
           │         └ ()
           └ <function run_command at 0x7fce29742158>
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
           │          │  │     │           └ {'host': '0.0.0.0', 'port': 5000, 'reload': True, 'debugger': False, 'eager_loading': True, 'with_threads': True}
           │          │  │     └ ()
           │          │  └ <flask.cli.ScriptInfo object at 0x7fce2c5d3e80>
           │          └ <function run_command at 0x7fce297420d0>
           └ <click.core.Context object at 0x7fce2c583898>
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'host': '0.0.0.0', 'port': 5000, 'reload': True, 'debugger': False, 'eager_loading': True, 'with_threads': True}
           │         └ (<flask.cli.ScriptInfo object at 0x7fce2c5d3e80>,)
           └ <function run_command at 0x7fce297420d0>
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 423, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
          │              │                                └ True
          │              └ <flask.cli.ScriptInfo object at 0x7fce2c5d3e80>
          └ <class 'flask.cli.DispatchingApp'>
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 152, in __init__
    self._load_unlocked()
    └ <flask.cli.DispatchingApp object at 0x7fce28d66ef0>
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
    │                └ <flask.cli.DispatchingApp object at 0x7fce28d66ef0>
    └ <flask.cli.DispatchingApp object at 0x7fce28d66ef0>
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
         │          └ <flask.cli.ScriptInfo object at 0x7fce2c5d3e80>
         └ <function locate_app at 0x7fce29831730>
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
               └ 'eudat.__main__'
  File "/code/eudat/__main__.py", line 26, in <module>
    app = create_app(name='REST_API')
          └ <function create_app at 0x7fce2628cf28>
  File "/usr/local/lib/python3.6/dist-packages/rapydo/server.py", line 153, in create_app
    project_init=init_mode, project_clean=destroy_mode
                 │                        └ False
                 └ False
  File "/usr/local/lib/python3.6/dist-packages/rapydo/services/detect.py", line 236, in init_services
    abackend=auth_backend
             └ <SQLAlchemy engine=None>
  File "/usr/local/lib/python3.6/dist-packages/rapydo/flask_ext/flask_irods/__init__.py", line 202, in custom_init
    return super().custom_init()
  File "/usr/local/lib/python3.6/dist-packages/rapydo/flask_ext/__init__.py", line 254, in custom_init
    return self.get_instance(
  File "/usr/local/lib/python3.6/dist-packages/rapydo/flask_ext/__init__.py", line 187, in get_instance
    obj = self.connect()
    │     └ <rapydo.flask_ext.flask_irods.IrodsPythonExt object at 0x7fce2405d438>
    └ None
  File "/usr/local/lib/python3.6/dist-packages/rapydo/flask_ext/__init__.py", line 110, in connect
    obj = self.retry()
    │     └ <rapydo.flask_ext.flask_irods.IrodsPythonExt object at 0x7fce2405d438>
    └ None
  File "/usr/local/lib/python3.6/dist-packages/rapydo/flask_ext/__init__.py", line 150, in retry
    raise e
  File "/usr/local/lib/python3.6/dist-packages/rapydo/flask_ext/__init__.py", line 148, in retry
    obj = self.custom_connection()
          └ <rapydo.flask_ext.flask_irods.IrodsPythonExt object at 0x7fce2405d438>
  File "/usr/local/lib/python3.6/dist-packages/rapydo/flask_ext/flask_irods/__init__.py", line 185, in custom_connection
    u = obj.users.get(self.user)
        │             └ <rapydo.flask_ext.flask_irods.IrodsPythonExt object at 0x7fce2405d438>
        └ <irods.session.iRODSSession object at 0x7fce24143940>
  File "/usr/local/lib/python3.6/dist-packages/irods/manager/user_manager.py", line 23, in get
    result = query.one()
             └ <irods.query.Query object at 0x7fce24143710>
  File "/usr/local/lib/python3.6/dist-packages/irods/query.py", line 223, in one
    results = self.execute()
              └ <irods.query.Query object at 0x7fce24143710>
  File "/usr/local/lib/python3.6/dist-packages/irods/query.py", line 172, in execute
    with self.sess.pool.get_connection() as conn:
  File "/usr/local/lib/python3.6/dist-packages/irods/pool.py", line 23, in get_connection
    conn = Connection(self, self.account)
           │          │     └ <irods.pool.Pool object at 0x7fce241432b0>
           │          └ <irods.pool.Pool object at 0x7fce241432b0>
           └ <class 'irods.connection.Connection'>
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 35, in __init__
    self._login_password()
    └ <irods.connection.Connection object at 0x7fce24143668>
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 277, in _login_password
    challenge = challenge_msg.get_main_message(AuthChallenge).challenge
                │                              └ <class 'irods.message.AuthChallenge'>
                └ <irods.message.iRODSMessage object at 0x7fce2411e6a0>
  File "/usr/local/lib/python3.6/dist-packages/irods/message/__init__.py", line 121, in get_main_message
    msg.unpack(ET.fromstring(self.msg))
    │          │             └ <irods.message.iRODSMessage object at 0x7fce2411e6a0>
    │          └ <module 'xml.etree.ElementTree' from '/usr/lib/python3.6/xml/etree/ElementTree.py'>
    └ <irods.message.AuthChallenge object at 0x7fce24143208>
  File "/usr/local/lib/python3.6/dist-packages/irods/message/message.py", line 35, in unpack
    self._values[name] = prop.unpack(root.findall(name))
    │            │       │           │            └ 'challenge'
    │            │       │           └ <Element 'authRequestOut_PI' at 0x7fce240478b8>
    │            │       └ <irods.message.property.BinaryProperty object at 0x7fce261f7978>
    │            └ 'challenge'
    └ <irods.message.AuthChallenge object at 0x7fce24143208>
  File "/usr/local/lib/python3.6/dist-packages/irods/message/property.py", line 33, in unpack
    return self.parse(el.text)
           │          └ <Element 'challenge' at 0x7fce24047f98>
           └ <irods.message.property.BinaryProperty object at 0x7fce261f7978>
  File "/usr/local/lib/python3.6/dist-packages/irods/message/property.py", line 74, in parse
    val = val.decode('utf-8') #
    │     └ b"\xdct\xa0D\x83O\x1d|\xca'By\xcbt\xe6\x94\xd2q*\xf9\xc7;v\xc1\xdai\x90\xca\x89\x84\xdd\x0flnd\x0b\xe8{8\xef0\xaf*\x17\xc99\xe0x...
    └ b"\xdct\xa0D\x83O\x1d|\xca'By\xcbt\xe6\x94\xd2q*\xf9\xc7;v\xc1\xdai\x90\xca\x89\x84\xdd\x0flnd\x0b\xe8{8\xef0\xaf*\x17\xc99\xe0x...
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 0: invalid continuation byte
root@rapydo_server:/code#

**Comment by adetorcy** [comment]
Does it work without flask? If possible I would try installing PRC in a virtual environment to see if it can connect to your iRODS server on its own, e.g:
```bash
virtualenv -p python3.6 testenv36
source testenv36/bin/activate
pip install python-irodsclient
python
```
```python
>>> from irods.session import iRODSSession
>>> with iRODSSession(host='your_host',
...                   port=1247,
...                   user='rods',
...                   password='*******************************',
...                   zone='tempZone') as session:
...     # do something that connects to the server
...     coll = session.collections.get('/tempZone/home/rods')
... 
>>> 
```

**Comment by massimo1962** [comment]
Hi Antoine,
thank you, this is the output  

VIRTUALENV (no-go)
==========
virtualenv -p python3.6 testenv36
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /code/testenv36/bin/python3.6
Not overwriting existing python script /code/testenv36/bin/python (you must use /code/testenv36/bin/python3.6)
Installing setuptools, pip, wheel...done.
root@rapydo_server:/code# source testenv36/bin/activate
(testenv36) root@rapydo_server:/code# pip install python-irodsclient
Requirement already satisfied: python-irodsclient in ./testenv36/lib/python3.6/site-packages
Requirement already satisfied: PrettyTable>=0.7.2 in ./testenv36/lib/python3.6/site-packages (from python-irodsclient)
(testenv36) root@rapydo_server:/code# python
Python 3.6.1 (default, Mar 22 2017, 06:17:05) 
[GCC 6.3.0 20170321] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from irods.session import iRODSSession
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/code/testenv36/lib/python3.6/site-packages/irods/session.py", line 4, in <module>
    from irods.query import Query
  File "/code/testenv36/lib/python3.6/site-packages/irods/query.py", line 5, in <module>
    from irods.models import Model
  File "/code/testenv36/lib/python3.6/site-packages/irods/models.py", line 3, in <module>
    import six
ModuleNotFoundError: No module named 'six'
>>> 





NO VIRTUALENV (no-go)
==============
 python
Python 3.6.1 (default, Mar 22 2017, 06:17:05) 
[GCC 6.3.0 20170321] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from irods.session import iRODSSession
>>> with iRODSSession(host='irods.rm.ingv.it', port=1247,user='rods',password='sdor', zone='INGV') as session:
...     coll = session.collections.get('/INGV/home/rods/san/archive/2016/IV/')
...     print (coll)
... 
test-MASSIMO {'encoding': None, 'confidence': 0.0, 'language': None}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/pool.py", line 21, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/irods/manager/collection_manager.py", line 16, in get
    result = query.one()
  File "/usr/local/lib/python3.6/dist-packages/irods/query.py", line 223, in one
    results = self.execute()
  File "/usr/local/lib/python3.6/dist-packages/irods/query.py", line 172, in execute
    with self.sess.pool.get_connection() as conn:
  File "/usr/local/lib/python3.6/dist-packages/irods/pool.py", line 23, in get_connection
    conn = Connection(self, self.account)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 35, in __init__
    self._login_password()
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 277, in _login_password
    challenge = challenge_msg.get_main_message(AuthChallenge).challenge
  File "/usr/local/lib/python3.6/dist-packages/irods/message/__init__.py", line 121, in get_main_message
    msg.unpack(ET.fromstring(self.msg))
  File "/usr/local/lib/python3.6/dist-packages/irods/message/message.py", line 35, in unpack
    self._values[name] = prop.unpack(root.findall(name))
  File "/usr/local/lib/python3.6/dist-packages/irods/message/property.py", line 33, in unpack
    return self.parse(el.text)
  File "/usr/local/lib/python3.6/dist-packages/irods/message/property.py", line 74, in parse
    val = val.decode('utf-8') #
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 1: invalid start byte
>>>

**Comment by adetorcy** [comment]
In your `/usr/local/lib/python3.6/dist-packages/irods/message/property.py`, can you try commenting out [these two lines](https://github.com/irods/python-irodsclient/blob/v0.6.0/irods/message/property.py#L70-L71)?

**Comment by massimo1962** [comment]
vi /usr/local/lib/python3.6/dist-packages/irods/message/property.py

    def parse(self, value):
        val = b64decode(value)
        #if six.PY3:
            #val = val.decode('utf-8') #
        return val




W VIRTUALENV

 python
Python 3.6.1 (default, Mar 22 2017, 06:17:05) 
[GCC 6.3.0 20170321] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from irods.session import iRODSSession
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/code/testenv36/lib/python3.6/site-packages/irods/session.py", line 4, in <module>
    from irods.query import Query
  File "/code/testenv36/lib/python3.6/site-packages/irods/query.py", line 5, in <module>
    from irods.models import Model
  File "/code/testenv36/lib/python3.6/site-packages/irods/models.py", line 3, in <module>
    import six
ModuleNotFoundError: No module named 'six'
>>> 




W/O VIRTUALENV

 python
Python 3.6.1 (default, Mar 22 2017, 06:17:05) 
[GCC 6.3.0 20170321] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from irods.session import iRODSSession
>>> iconnection = {'host': 'irods', 'password': '******', 'user': '******', 'zone': '*****', 'port': '1247'}
>>> session = iRODSSession(**iconnection)
>>> print (session)
<irods.session.iRODSSession object at 0x7f35d97af390>
>>> coll = session.collections.get('/ZONE/home/rods/san/archive/2016/XX/')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/pool.py", line 21, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/irods/manager/collection_manager.py", line 16, in get
    result = query.one()
  File "/usr/local/lib/python3.6/dist-packages/irods/query.py", line 223, in one
    results = self.execute()
  File "/usr/local/lib/python3.6/dist-packages/irods/query.py", line 172, in execute
    with self.sess.pool.get_connection() as conn:
  File "/usr/local/lib/python3.6/dist-packages/irods/pool.py", line 23, in get_connection
    conn = Connection(self, self.account)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 35, in __init__
    self._login_password()
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 279, in _login_password
    challenge = challenge.encode('utf-8').strip()
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by adetorcy** [comment]
I pushed some changes. Please try the latest code and let me know how it goes. In your virtual environment you will need to run `pip install XXX` whenever you see `ModuleNotFoundError: No module named 'XXX'`.

**Comment by adetorcy** [comment]
Closing this due to inactivity but feel free to reopen if the problem persists.
