### ISSUE TITLE
no attribute 'exc_clear' with python3 in data_object

### ISSUE THREAD

**Issue by nyanloutre** [irods/python-irodsclient#94]
Hi,

When I run objects = collection.data_objects I get an exception : 
```python
Traceback (most recent call last):
  File "/home/trehiou/.local/lib/python3.5/site-packages/irods/data_object.py", line 46, in __init__
    setattr(self, attr, results[0][value])
KeyError: <irods.column.Column 422 D_RESC_HIER>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trehiou/PycharmProjects/irods_python/main.py", line 22, in <module>
    objects = login_collection.data_objects
  File "/home/trehiou/.local/lib/python3.5/site-packages/irods/collection.py", line 44, in data_objects
    for _, replicas in grouped
  File "/home/trehiou/.local/lib/python3.5/site-packages/irods/collection.py", line 44, in <listcomp>
    for _, replicas in grouped
  File "/home/trehiou/.local/lib/python3.5/site-packages/irods/data_object.py", line 49, in __init__
    sys.exc_clear()
AttributeError: module 'sys' has no attribute 'exc_clear'
```

Am I doing something wrong or is it a bug ?

The line can be found here https://github.com/irods/python-irodsclient/blob/master/irods/data_object.py#L49

As a temporary workaround I edited this line with a try catch : 
```python
try:
   sys.exc_clear()
except:
   pass
```

**Comment by adetorcy** [comment]
Which iRODS version are you connecting to?

**Comment by adetorcy** [comment]
Python 3 doesn't have sys.exc_clear() ([doc](https://docs.python.org/3/whatsnew/3.0.html#index-22)). It's probably not necessary to clear the exception anyway. I'll push a fix.

Thanks

**Comment by nyanloutre** [comment]
Nice ! Thanks
