### ISSUE TITLE
Register files and directories

### ISSUE THREAD

**Issue by adetorcy** [irods/python-irodsclient#95]
As in https://docs.irods.org/4.2.1/icommands/user/#ireg

**Comment by froggleston** [comment]
Does this function support recursive ireg? There's no example showing if there's an option that needs to be passed to automatically ireg all collections and files underneath a supplied parent collection.

**Comment by trel** [comment]
I believe the collection registration is always recursive.

https://github.com/irods/python-irodsclient/commit/3b6d17bc5a5009944c70340548db561b1e35d3a4#diff-f0dd7addebd57e616c3a212730b35aa2R278

**Comment by froggleston** [comment]
Strange. I try to register an existing physical path to a non-existent iRODS collection (the parent collection does exist, as per the iRODS path I have supplied below - the real path I've obviously obfuscated). On the command line with ireg -C, I would expect this to create any ancestor collections necessary.

> Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/lib/python2.7/site-packages/channels/sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/channels/sessions.py", line 141, in inner
    func(message, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/channels/sessions.py", line 54, in inner
    return func(*args, **kwargs)
  File "/opt/grassroots/apache/htdocs/ena_search_django/ena/ena/consumers.py", line 56, in ws_message
    irods.register(data, reply_channel)
  File "/opt/grassroots/apache/htdocs/ena_search_django/ena/utils/irods_utils.py", line 44, in register
    session.collections.register(dest_local, dest_irods)
  File "/usr/lib/python2.7/site-packages/irods/manager/collection_manager.py", line 139, in register
    response = conn.recv()
  File "/usr/lib/python2.7/site-packages/irods/connection.py", line 92, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
CAT_UNKNOWN_COLLECTION: collection '/parent/path/to/non/existent/collection' is unknown
