### ISSUE TITLE
Dependency module six

### ISSUE THREAD

**Issue by stolpeo** [irods/python-irodsclient#99]
Hello,

I want to build a [conda forge](https://conda-forge.org/) recipe for the [python irodsclient](https://github.com/bihealth/staged-recipes/blob/python-irodsclient/recipes/python-irodsclient/meta.yaml). When it comes to their CI tests, it fails because it is lacking the module `six`. Should it be included in the `setup.py` as a requirement?

Cheers,
  Oliver

```
+ source /opt/conda/bin/activate /staged-recipes/build_artefacts/python-irodsclient_1511861525437/_t_env
+ /staged-recipes/build_artefacts/python-irodsclient_1511861525437/_t_env/bin/python -s /staged-recipes/build_artefacts/python-irodsclient_1511861525437/test_tmp/run_test.py
import: 'irods'
import: 'irods.message'
Traceback (most recent call last):
  File "/staged-recipes/build_artefacts/python-irodsclient_1511861525437/test_tmp/run_test.py", line 5, in <module>
    import irods.message
  File "/staged-recipes/build_artefacts/python-irodsclient_1511861525437/_t_env/lib/python2.7/site-packages/irods/message/__init__.py", line 8, in <module>
    from irods.message.message import Message
  File "/staged-recipes/build_artefacts/python-irodsclient_1511861525437/_t_env/lib/python2.7/site-packages/irods/message/message.py", line 3, in <module>
    from irods.message.ordered import OrderedMetaclass, OrderedClass
  File "/staged-recipes/build_artefacts/python-irodsclient_1511861525437/_t_env/lib/python2.7/site-packages/irods/message/ordered.py", line 5, in <module>
    import six
ImportError: No module named six
TESTS FAILED: python-irodsclient-0.6.0-py27_0.tar.bz2
Exited with code 1
```

**Comment by trel** [comment]
Is this not already handled?

`setup.py` already names `six` in the `install_requires` array.

  https://github.com/irods/python-irodsclient/blob/master/setup.py#L31

**Comment by stolpeo** [comment]
Thanks for your answer! I'm using the current pypi package for that (0.6.0), and it's not in there:

https://pypi.python.org/pypi/python-irodsclient
https://github.com/irods/python-irodsclient/blob/v0.6.0/setup.py

When will be the new version released on pypi?

**Comment by adetorcy** [comment]
0.7.0 is around the corner. Early December.
